
[routing]
max_allowed_parameter_len=20
                # maximum length of a parameter name.

max_allowed_request_body_size=16 * 1024 * 1024
                # maximum size of the body of a request, including files.
                
[executable]
id_service=$ID_SERVICE$
                # identification of the application within the DB:

command_line=$COMMAND_LINE$
                # list of command line and (if needed) parameters to invoke the code.
                # Additional parameters from the request will be added at runtime.
                #
                # To run non-python projects using venv, consider:
                # -) installing venv-run in the venv running this application,
                # -) setting the parameter "working_directory" to the venv of the non-python working directory,
                # -) setting the parameter command_line as follow:
                # command_line=['venv-run', 'my-non-python-app']

file_root_directory=$BASE_DIRECTORY$
                # base directory where to write input and output file(s).
                # Input files will be saved, output files will be written, to the directory:
                # file_root_directory + '/' + id_request + '/' + filename

suppress_stdout=$SUPPRESS_STDOUT$


